/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vwrotahqappyxonixpnj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3cm90YWhxYXBweXhvbml4cG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MTg5NTksImV4cCI6MjA4ODQ5NDk1OX0.EuQk-WrUcnUyCGM1AXFRn3av-izM09kLGMwpgK1YXwc"